config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    
    
    root to: "home#index" 
    get '/dashboard', to: 'dashboard#index'
    resources :bathroom_locations do
        resources :reviews
    end
    
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
#        response = Excon.get('https://data.cityofnewyork.us/resource/r27e-u3sy.json')
#        @my_response = JSON.parse(response.body)
#        @my_response.each do |my_response|
##            BathroomLocation.create(
#                borough: 'my_response['borough']',
#                location: 'my_response['location']',
#                name: 'my_response['name']',
#                open_year_round: 'my_response['open_year_round']'
#                
#                )
        
         @my_restrooms = BathroomLocation.all
        
#        @bathroom_location = BathroomLocation.find(params[:id])
#        results = Geocoder.search('my_response['location']')
#        @my_result= results.first.coordinates
        
    end
    
    
    
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
              
<% @my_restrooms.each_with_index do |restroom, index| %>
    <div class="location" data-latitude="<%=restroom.latitude %>" data-longitude="<%= restroom.longitude %>" data-name ='<%= restroom.name %>' data-location='<%= restroom.location %>' data-borough='<%= restroom.borough %>' data-open='<%= restroom.open_year_round %>' data-user='<%= restroom.user_id %>' data-id='<%= restroom.id %>'></div>
<% end %>

  


<div class="col-12 info">
    <div class="row image-placeholder">
       <div class="col-12 dashboard-image">
          
       </div>
   </div>
   <div class ='marker-details box'>
    <div class="row info-display">
        <div class="col-4 align-right">
            <strong>Name: </strong><br>
            <strong>Location:  </strong><br>
            <strong>Borough: </strong><br>
            <strong>Open Year Round: </strong><br>
<!--            <strong>User: </strong><br>-->
            <strong>Avr Rating: </strong><br>
        </div>

        <div class="col-8 aling-left">
            <p class = 'bathroom_name'> </p>
            <p class = 'bathroom_location'></p>
            <p class = 'bathroom_borough'></p>
            <p class = 'bathroom_open'></p>
            <p class = 'bathroom_user'></p>
            <p class = 'bathroom_id'></p>

        </div>
  
    </div>            
       
    <div class = 'row'>
        <div class="col-4 align-right">
            
            <strong>Mode of Travel: </strong>
        </div>
        <div class="col-8 aling-left">
            <select id="mode">
            <option value="DRIVING">Driving</option>
            <option value="WALKING">Walking</option>
            <option value="BICYCLING">Bicycling</option>
            <option value="TRANSIT">Transit</option>
            </select> 
        </div>

    </div>    
   
   
    <ul class="rate-area">

        <input type="radio" id="5-star" name="rating" value="5" /><label for="5-star" title="Amazing">5 stars</label>
        <input type="radio" id="4-star" name="rating" value="4" /><label for="4-star" title="Good">4 stars</label>
        <input type="radio" id="3-star" name="rating" value="3" /><label for="3-star" title="Average">3 stars</label>
        <input type="radio" id="2-star" name="rating" value="2" /><label for="2-star" title="Not Good">2 stars</label>
        <input type="radio" id="1-star" name="rating" value="1" /><label for="1-star" title="Bad">1 star</label>

    </ul>
    <div class="comment">
    </div>
</div> 
  
  
<div>
   
   
       
        <%#= #link_to 'Leave a comment', new_bathroom_location_review_path(stats[i].id), class: "btn btn-outline-primary btn-block mt-3" %>
    </div>
</div>
  
<div id="directionsPanel" style="width:80%;height 100%"></div>  
   
    
    
<!---
#        let restrooms = document.querySelectorAll('.location');
#        let myBathroom = restrooms[0];
#        myBathroom.getAttribute('data-latitude');
#        myBathroom.getAttribute('data-longitude');
#-->