config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    
    
    root to: "home#index" 
    get '/dashboard', to: 'dashboard#index'
    resources :bathroom_locations do
        resources :reviews
    end
    
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bathroom_location.rb
class BathroomLocation < ApplicationRecord
#  commented out because we don't need it no more after we got data from API and pushed it into database, then saved to .csv file and  created a new task to populate  it before deployment
    belongs_to :user
    has_many :reviews
    
    geocoded_by :address_from_components
    after_validation :geocode
     
    
    private
    def address_from_components
    	# puts '::::::::::::  geocode :::::::::::'
        "#{location}, #{borough}"
    end
end

app/models/restroom.rb
class Restroom < ApplicationRecord
#    geocoded_by :address
#    after_validation :geocode
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :bathroom_location
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
    has_many :bathroom_locations
    has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/bathroom_locations_controller.rb
class BathroomLocationsController < ApplicationController
    def index
        @bathroom_locations = BathroomLocation.all
    end
    
    def new
        @bathroom_location = BathroomLocation.new
    end
    
    def create
        new_bathroom_location = BathroomLocation.create(bathroom_location_params.merge(user_id: current_user.id))
       
        redirect_to dashboard_path
    end
    
    def show
        @bathroom_location = BathroomLocation.find(params[:id])
    end
    
#    def edit
#        @bathroom_location = BathroomLocation.find(params[:id])
#    end
#    
#    def update
#        bathroom_location = BathroomLocation.find(params[:id])
#        bathroom_location.update(bathroom_location_params)
#        
#    end
#    
#    def destroy
#        
#    end
#    
    
    private
    def bathroom_location_params
        params.require(:bathroom_location).permit(:borough, :location, :name, :open_year_round)
    end
    
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
#        response = Excon.get('https://data.cityofnewyork.us/resource/r27e-u3sy.json')
#        @my_response = JSON.parse(response.body)
#        @my_response.each do |my_response|
##            BathroomLocation.create(
#                borough: 'my_response['borough']',
#                location: 'my_response['location']',
#                name: 'my_response['name']',
#                open_year_round: 'my_response['open_year_round']'
#                
#                )
        
         @my_restrooms = BathroomLocation.all
        
#        @bathroom_location = BathroomLocation.find(params[:id])
#        results = Geocoder.search('my_response['location']')
#        @my_result= results.first.coordinates
        
    end
    
    
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
     def index
         @my_restrooms = BathroomLocation.all
        if user_signed_in?
           return redirect_to dashboard_path 
        end
    end
    
end

app/controllers/restrooms_controller.rb
class RestroomsController < ApplicationController
    def index
        @restrooms = Restroom.all
    end
     
    def new
    end
    
    def create
    end
    
    def edit
    end
    
    def show
        
    end
    
    def destroy
    end
    
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
    end
    
    def new
        @review = Review.new
    end
    
    def create
        bathroom_location = Bathroom_location.find(params[:bathroom_location_id])
        new_review = bathroom_location.reviews.create(review_params.merge(user_id: current_user.id))  
        redirect_to dashboard_path
    end
    
    def show
    end
    
    def edit
    end
    
    def update
    end
    
    def destroy
    end
    
    
    private
    def review_params
        params(:review).permit(:comment)
    
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bathroom_locations_helper.rb
module BathroomLocationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restrooms_helper.rb
module RestroomsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>FindPublicRestroom</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
    </head>

    <body class="<%= controller_name %> <%= action_name %>">
     
           

            <nav class="navbar navbar-expand-lg ">
                <a class="navbar-brand" href="/"><span class='logo'>Gottago</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                   
                   <% if user_signed_in? %>
                    <div class="navbar-nav">
                        <%= link_to 'Home', dashboard_path, class: 'nav-item nav-link active' %> <span class="sr-only">(current)</span>
                        <%= link_to 'Add review', dashboard_path, class: 'nav-item nav-link' %>
                        <%= link_to 'Add a Bathroom', new_bathroom_location_path, class: 'nav-item nav-link' %>
                        <%= link_to 'Log Out', destroy_user_session_path, method: 'DELETE', class: 'logout nav-item nav-link' %>

                    </div>
                    <% else %>
                    
                     <div class="navbar-nav">
                        <h4 class='msg'><em>To add a bathroom or leave a review, please</em></h4>
                        <%= link_to "Log In", new_user_session_path, class: 'btn btn-outline-info nav-btn' %>
                        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-outline-info nav-btn' %>

                    </div>
                    
                    <% end %>
                </div>
            </nav>

       
        

        <div class="container">
            <div class="row">
                <div class="col-6">
                   
                    <div id="map_wrapper">
                    <div id="map_canvas" class="mapping"></div>
                    </div> 
                </div>
                <div class="col-6">
       
                    <% #if notice %>
<!--
                        <p class="alert alert-success"><%#= notice %></p>
                    <%# end %>
                    <%# if alert %>
                        <p class="alert alert-danger"><%#= alert %></p>
                    <%# end %>
-->
                   
                    <%= yield %>
                </div>
            </div>
        </div>

    </body>
       <footer>
            &copy; 2018 Minimal Website&nbsp;<span class="separator">|</span> Design by <a id="myName" href="http://www.irynamanu.com">Iryna Manu</a>
        </footer>
</html>